### ISSUE TITLE
3000 вынести в константу с говорящим именем

### ISSUE THREAD

**Issue by coursar** [Nikolay0951/dz2-tinkoff#1]
https://github.com/Nikolay0951/dz2-tinkoff/blob/8792ebc9bcd3e8823f1d5028c53bcca4cac3e44f/app.js#L6

**Comment by Nikolay0951** [comment]
Здравствуйте! Проверьте пожалуйста dz2

**Comment by coursar** [comment]
Если сделали - закрывайте issue
